import {
  BadgeIndianRupee,
  ClipboardList,
  FileText,
  Handshake,
  Package,
  PhoneIncoming,
  Receipt,
  RefreshCw,
  Truck,
  UserCheck,
  Wrench,
} from 'lucide-react'
import type { FlowStage } from './AnimatedFlow'
import {
  AmcMini,
  AssignMini,
  InvoiceMini,
  JobCreatedMini,
  LeadMini,
  PartsMini,
  PaymentMini,
  QuoteMini,
  RequestMini,
  ServiceMini,
  TechnicianMini,
} from './stageMinis'

/** Home page: Customer Request → Job Assignment → Technician → Service → Parts → Invoice → Payment */
export const HOME_FLOW: FlowStage[] = [
  {
    id: 'request',
    label: 'Customer request',
    icon: PhoneIncoming,
    heading: 'Every request lands in one place',
    text: 'Calls, walk-ins and enquiries become service requests linked to the customer and the exact AC unit, so nothing lives on paper or gets lost in a chat.',
    chips: ['Customer record', 'Unit & warranty check', 'Priority'],
    detail: <RequestMini />,
  },
  {
    id: 'assignment',
    label: 'Job assignment',
    icon: UserCheck,
    heading: 'Assign the right technician in seconds',
    text: 'See who is free, who is nearest and who has the right skills, then assign the job. The schedule updates for the whole team.',
    chips: ['Skills & distance', 'Live workload', 'One-tap assign'],
    detail: <AssignMini />,
  },
  {
    id: 'technician',
    label: 'Technician',
    icon: Truck,
    heading: 'The technician gets the job on their phone',
    text: 'Address, customer history, checklist and parts list arrive on the technician app, and the customer knows who is coming and when.',
    chips: ['Technician app', 'Route & ETA', 'Customer notified'],
    detail: <TechnicianMini />,
  },
  {
    id: 'service',
    label: 'Service',
    icon: Wrench,
    heading: 'Work is recorded as it happens',
    text: 'Checklists, readings, photos and notes are captured on site, so every AC service has a record you can trust.',
    chips: ['Checklists', 'Photos', 'Service report'],
    detail: <ServiceMini />,
  },
  {
    id: 'parts',
    label: 'Parts',
    icon: Package,
    heading: 'Spare parts follow the job',
    text: 'Parts used come off van or warehouse stock and go onto the invoice, with a reorder alert before a common part runs out.',
    chips: ['Van & warehouse stock', 'Low-stock alerts', 'Parts on invoice'],
    detail: <PartsMini />,
  },
  {
    id: 'invoice',
    label: 'Invoice',
    icon: Receipt,
    heading: 'An invoice that writes itself',
    text: 'Labour, parts and visit charges flow from the completed job into the invoice, ready to send while the technician is still on site.',
    chips: ['From the job', 'Parts & labour', 'Customer copy'],
    detail: <InvoiceMini />,
  },
  {
    id: 'payment',
    label: 'Payment',
    icon: BadgeIndianRupee,
    heading: 'Know what is paid and what is pending',
    text: 'Payments are recorded against the invoice and the customer, so follow-ups start from facts instead of memory.',
    chips: ['Payment status', 'Customer ledger', 'Pending follow-up'],
    detail: <PaymentMini />,
  },
]

/** HVAC page: Lead → Quotation → Job → Technician → Service → Parts → Invoice → Payment → AMC */
export const HVAC_FLOW: FlowStage[] = [
  {
    id: 'lead',
    label: 'Lead',
    icon: Handshake,
    heading: 'Capture every enquiry before it goes cold',
    text: 'New installation and service enquiries are logged with source, requirement and a follow-up date, so the sales pipeline stays visible.',
    chips: ['Lead source', 'Follow-up reminders', 'Pipeline'],
    detail: <LeadMini />,
  },
  {
    id: 'quotation',
    label: 'Quotation',
    icon: FileText,
    heading: 'Send a clear quotation the same day',
    text: 'Build quotes from your own price list of units, pipes, gas and labour, send them for approval and track the answer.',
    chips: ['Price list', 'Approval status', 'Revisions'],
    detail: <QuoteMini />,
  },
  {
    id: 'job',
    label: 'Job',
    icon: ClipboardList,
    heading: 'Approved quote becomes a work order',
    text: 'Items, price and site details carry over into the job, with the right checklist template for installation, repair or maintenance.',
    chips: ['Work order', 'Checklist template', 'Schedule'],
    detail: <JobCreatedMini />,
  },
  {
    id: 'technician',
    label: 'Technician',
    icon: Truck,
    heading: 'Assign by skill, distance and workload',
    text: 'Dispatch to the technician who fits the job. They get everything on the app and the customer gets an ETA.',
    chips: ['Scheduling', 'Technician app', 'ETA to customer'],
    detail: <AssignMini />,
  },
  {
    id: 'service',
    label: 'Service',
    icon: Wrench,
    heading: 'Record the work, not just the visit',
    text: 'Checklists, gas readings, photos and notes are saved against the job and the AC unit for the next technician to see.',
    chips: ['Checklists', 'Readings & photos', 'Unit history'],
    detail: <ServiceMini />,
  },
  {
    id: 'parts',
    label: 'Parts',
    icon: Package,
    heading: 'Spare parts tracked to the job',
    text: 'Compressor capacitors, gas, pipes and PCBs are deducted from van or warehouse stock and billed with the job.',
    chips: ['Van stock', 'Low-stock alerts', 'Costing'],
    detail: <PartsMini />,
  },
  {
    id: 'invoice',
    label: 'Invoice',
    icon: Receipt,
    heading: 'Invoice from the completed job',
    text: 'No re-typing at the office. Labour, parts and visit charges roll into the invoice automatically.',
    chips: ['Auto-built', 'Parts & labour', 'Send to customer'],
    detail: <InvoiceMini />,
  },
  {
    id: 'payment',
    label: 'Payment',
    icon: BadgeIndianRupee,
    heading: 'Payment follow-up without the chasing',
    text: 'See pending invoices by customer and age, and record payments as they arrive.',
    chips: ['Pending list', 'Customer ledger', 'Reminders'],
    detail: <PaymentMini />,
  },
  {
    id: 'amc',
    label: 'AMC',
    icon: RefreshCw,
    heading: 'Turn one job into repeat revenue',
    text: 'Annual maintenance contracts schedule their own visits and remind you before renewal, so service customers keep coming back.',
    chips: ['AMC contracts', 'Visit schedule', 'Renewal alerts'],
    detail: <AmcMini />,
  },
]

