/**
 * Static prerender.
 *   1. `vite build`                         → dist/  (client bundle + index.html template)
 *   2. `vite build --ssr src/entry-server`  → dist-ssr/entry-server.js
 *   3. this script renders every approved route to dist/<route>/index.html,
 *      injects the page's <title>/meta/JSON-LD and modulepreload hints,
 *      and writes sitemap.xml, 404.html and Netlify's _redirects.
 */
import fs from 'node:fs'
import path from 'node:path'
import { pathToFileURL } from 'node:url'

const root = process.cwd()
const dist = path.join(root, 'dist')
const ssrEntry = path.join(root, 'dist-ssr', 'entry-server.js')

// dist/index.html is overwritten by the home page output below, so keep a pristine copy of the
// template. `vite build` empties dist/, so a stale copy can never survive into a new build.
const templateCopy = path.join(dist, '.template.html')
if (!fs.existsSync(templateCopy)) fs.copyFileSync(path.join(dist, 'index.html'), templateCopy)
const template = fs.readFileSync(templateCopy, 'utf8')
if (!template.includes('<!--app-html-->')) throw new Error('dist/.template.html is not the pristine Vite template — run a full build.')
const manifest = JSON.parse(fs.readFileSync(path.join(dist, '.vite', 'manifest.json'), 'utf8'))
const server = await import(pathToFileURL(ssrEntry).href)

const SITE_URL = 'https://fsmflow.in'

/** Collect a chunk and its static imports (excluding the entry, which index.html already loads). */
function chunkGraph(file) {
  const out = new Set()
  const walk = (key) => {
    const entry = manifest[key]
    if (!entry || out.has(entry.file)) return
    if (!entry.isEntry) out.add(entry.file)
    for (const dep of entry.imports ?? []) walk(dep)
  }
  walk(file)
  return [...out]
}

function write(file, contents) {
  fs.mkdirSync(path.dirname(file), { recursive: true })
  fs.writeFileSync(file, contents)
}

function outputPath(route) {
  return route === '/' ? path.join(dist, 'index.html') : path.join(dist, route.replace(/^\//, ''), 'index.html')
}

async function renderPage(url, { noindex = false } = {}) {
  const { html, seo, pageFile } = await server.render(url)
  if (!seo) throw new Error(`Page ${url} did not render a <Seo/> — every page must declare its metadata.`)
  const head = server.buildHead(noindex ? { ...seo, noindex: true } : seo)
  const preloads = pageFile ? chunkGraph(pageFile).map((f) => `<link rel="modulepreload" crossorigin href="/${f}" />`) : []
  const headHtml = [server.headToHtml(head), ...preloads].join('\n    ')
  return template.replace('<!--seo-head-->', headHtml).replace('<!--app-html-->', html)
}

const routes = server.getAllRoutes()
let count = 0
for (const { path: route } of routes) {
  write(outputPath(route), await renderPage(route))
  count++
}

// 404 page (not in the sitemap, noindex)
write(path.join(dist, '404.html'), await renderPage('/__not-found__', { noindex: true }))

// Sitemap
const today = new Date().toISOString().slice(0, 10)
const urls = routes
  .map(
    (r) =>
      `  <url>\n    <loc>${SITE_URL}${r.path === '/' ? '/' : r.path}</loc>\n    <lastmod>${today}</lastmod>\n    <changefreq>${r.changefreq}</changefreq>\n    <priority>${r.priority.toFixed(1)}</priority>\n  </url>`,
  )
  .join('\n')
write(path.join(dist, 'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`)

// Netlify: serve each clean URL straight from <route>/index.html with a forced 200 rewrite (the "!").
// Without it Netlify may redirect /pricing → /pricing/, which would fight the no-trailing-slash canonicals.
// (Other hosts ignore this file; Apache uses public/.htaccess.)
const rewrites = routes.filter((r) => r.path !== '/').map((r) => `${r.path}  ${r.path}/index.html  200!`)
write(path.join(dist, '_redirects'), ['# Generated by scripts/prerender.mjs — do not edit.', ...rewrites, ''].join('\n'))

// Machine-readable route list for the audit script.
write(path.join(dist, '.routes.json'), JSON.stringify(routes.map((r) => r.path)))

console.log(`Prerendered ${count} pages + 404.html + sitemap.xml`)
